sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=process.env.CC_TEST_REPORTER_ID

language: node_js

node_js:
  - "v11.0.0"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - yarn install

script:
  - yarn run jest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
  - yarn run test
  - yarn run codecov
