sudo: false

env:
  global:
    - CC_TEST_REPORTER_ID=df12eef77117e18e040c00aa04d01fd26b503e250181c7c20c9c2138e00c6d63

language: node_js

node_js:
  - "stable"

cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g yarn

install:
  - yarn install

services:
  - postgresql

before_script:
  - psql -c 'create database wayfarertestdb;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn run jest

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - yarn run test
